#!/usr/bin/env python3
"""
Job Analyst & Skill Matcher
---------------------------
Reads job_listings_database.json, calculates candidate match percentage
based on weighted tech stack keywords, and generates a formatted Markdown report.
"""

import json
from datetime import datetime
from pathlib import Path

BASE_DIR = Path(__file__).parent.resolve()
DB_FILE = BASE_DIR / "job_listings_database.json"
OUTPUT_MD = BASE_DIR / "relevant_job_matches.md"

# Weighted skill keywords for match calculation
KEYWORDS_WEIGHTS = {
    # Core technical skills (High weight)
    "kotlin": 15,
    "android": 15,
    "react": 12,
    "typescript": 12,
    "javascript": 10,
    "js": 8,
    "firebase": 12,
    "sql": 10,
    "java": 10,
    "mobile": 10,
    
    # Frameworks & core concepts
    "fullstack": 10,
    "frontend": 10,
    "backend": 10,
    "api": 8,
    "git": 6,
    "rest": 6,
    "ui": 6,
    "ux": 6,
    "python": 8,
    "systemutvikler": 10,
    "programvareutvikler": 10,
    
    # Collaboration & soft skills
    "team": 6,
    "samarbeid": 6,
    "frivillig": 8,
    "ledelse": 6,
    "koordinator": 6,
    "agile": 5,
    "smidig": 5,
    "brukergrensesnitt": 6,
    "tverrfaglig": 5
}

def load_database():
    if DB_FILE.exists():
        with open(DB_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return {}

def save_database(db):
    with open(DB_FILE, "w", encoding="utf-8") as f:
        json.dump(db, f, ensure_ascii=False, indent=2)

def calculate_match(job_title, description_text):
    text = (job_title + " " + description_text).lower()
    score = 0
    max_possible = 100
    matched_skills = []

    for kw, weight in KEYWORDS_WEIGHTS.items():
        if kw in text:
            score += weight
            matched_skills.append(kw.capitalize())

    # Normalize score to percentage (max 100%)
    match_pct = min(100, int((score / max_possible) * 100))
    
    unique_matches = list(dict.fromkeys(matched_skills))[:5]
    if unique_matches:
        analysis = f"Matched skills: {', '.join(unique_matches)}"
    else:
        analysis = "General Software Engineering Position"

    return match_pct, analysis

def generate_markdown(db):
    analyzed_jobs = []
    excluded_jobs = []

    for job_id, job in db.items():
        if job.get("status") == "excluded":
            excluded_jobs.append(job)
        else:
            analyzed_jobs.append(job)

    # Sort matched jobs by match percentage (descending)
    analyzed_jobs.sort(key=lambda x: x.get("match_percentage", 0), reverse=True)

    now_str = datetime.now().strftime("%Y-%m-%d %H:%M")

    md = []
    md.append("# 🎯 Job Match Analysis Report")
    md.append(f"\n*Last updated: {now_str}*\n")
    md.append("This document is generated by `job_analyst.py`. Positions are scored based on tech stack match.\n")
    
    md.append("---")
    md.append("\n## 🌟 Open Developer Positions (Sorted by Match %)\n")
    md.append("| Match % | Position Title | Company | Location | Deadline | Link |")
    md.append("| :---: | :--- | :--- | :--- | :---: | :---: |")

    for job in analyzed_jobs:
        pct = job.get("match_percentage", 0)
        title = job.get("title", "Unknown")
        company = job.get("company", "Unknown")
        location = job.get("location", "Unknown")
        deadline = job.get("application_deadline", "Unknown")
        url = job.get("url", "#")
        
        md.append(f"| **{pct}%** | {title} | {company} | {location} | {deadline} | [View Listing]({url}) |")

    md.append("\n---")
    md.append("\n## 🔍 Match Breakdown\n")

    for job in analyzed_jobs[:20]: # Top 20 listings
        pct = job.get("match_percentage", 0)
        title = job.get("title", "Unknown")
        company = job.get("company", "Unknown")
        url = job.get("url", "#")
        analysis = job.get("match_analysis", "No analysis available.")

        md.append(f"### [{title}]({url}) - {company} ({pct}% Match)")
        md.append(f"* **Location:** {job.get('location', 'Unknown')} | **Deadline:** {job.get('application_deadline', 'Unknown')}")
        md.append(f"* **Analysis:** {analysis}")
        md.append("")

    with open(OUTPUT_MD, "w", encoding="utf-8") as f:
        f.write("\n".join(md))

    print(f"[+] Exported updated {OUTPUT_MD.name} with {len(analyzed_jobs)} matching positions.")

def run_analyst():
    print("🧠 Starting Job Analyst...")
    db = load_database()
    
    updated_count = 0
    for job_id, job in db.items():
        if job.get("status") == "excluded":
            continue
        
        match_pct, analysis = calculate_match(job.get("title", ""), job.get("description_text", ""))
        job["match_percentage"] = match_pct
        job["match_analysis"] = analysis
        job["status"] = "analyzed"
        updated_count += 1

    save_database(db)
    generate_markdown(db)
    print(f"✨ Analyst completed: Processed {updated_count} job postings.")

if __name__ == "__main__":
    run_analyst()
